# Generated by Django 3.2.4 on 2021-06-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_projects',
            name='info',
        ),
        migrations.AddField(
            model_name='sub_projects',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
