# Generated by Django 3.2.4 on 2021-06-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20210607_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_projects',
            name='completed',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
